source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.2'
use_frameworks!

target 'Ventio' do
	pod 'Swinject'
	pod 'SwinjectStoryboard'
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'SVProgressHUD'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Cosmos'
	pod 'Kingfisher'
end
